# Generated by Django 2.2.28 on 2023-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('provides_card', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
